### ISSUE TITLE
Post Tags on the Discover Page — Display Bug

### ISSUE THREAD

**Issue by swyoung** [michaelschofield/radian#10]
Some post tags on the Discover page are displaying red text on red background without the white border, and turn white on mouse over.
<img width="930" alt="screen shot 2017-10-26 at 2 39 41 pm" src="https://user-images.githubusercontent.com/4831255/32053403-87b6c8ae-ba5b-11e7-89eb-2fb9e301da5e.png">

**Comment by michaelschofield** [comment]
Oh, great catch. In this case, one is a category and the other is a tag, and I missed styling the latter appropriately. Fixed.
