### ISSUE TITLE
Single post footer issue

### ISSUE THREAD

**Issue by ryerbanta** [michaelschofield/radian#9]
Looks like there's a bit of rogue code appearing in the post footer. Right before the tags. 
cd wp-content/themes/

I poked around a bit, but didn't find where this is coming from. Figure you'll have a much better time zeroing in on this.

- The site is looking so great though. Thank you so much for making our designs a reality. Great work.

**Comment by michaelschofield** [comment]
Great catch! I think this was submitted as another issue which I just now tweaked in the next release, so I'm going to close this issue <3.
